# Generated by Django 5.0.1 on 2024-02-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0001_post_subscription_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subscription',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcribers', to='ModalsDateBase.catigory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
