# Generated by Django 5.0.1 on 2024-01-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profil_post',
            new_name='author',
        ),
    ]
