# Generated by Django 5.0.1 on 2024-02-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0002_remove_post_subscription_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='ModalsDateBase.catigory'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(to='ModalsDateBase.author'),
        ),
    ]
