# Generated by Django 5.0.1 on 2024-01-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0002_rename_profil_post_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_rating_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
