# Generated by Django 5.0.1 on 2024-02-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0003_best_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catigory',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='post',
            name='catigory_post',
        ),
        migrations.AddField(
            model_name='catigory',
            name='category',
            field=models.CharField(default=2, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='ModalsDateBase.catigory'),
        ),
    ]
