# Generated by Django 5.0.1 on 2024-02-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0006_alter_catigory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModalsDateBase.author')),
                ('user_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModalsDateBase.post')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModalsDateBase.authorpost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModalsDateBase.authorpost'),
        ),
    ]
