# Generated by Django 5.0.1 on 2024-02-17 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0008_alter_post_author_alter_author_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcribers', to='ModalsDateBase.catigory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
